// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcist4Xcc_CLd_C9Hzs8zR2kFYcjkkmbY',
    appId: '1:551556042270:web:f555cb15dd43dd1788280f',
    messagingSenderId: '551556042270',
    projectId: 'chikoropro',
    authDomain: 'chikoropro.firebaseapp.com',
    storageBucket: 'chikoropro.firebasestorage.app',
    measurementId: 'G-161RL82QJ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5DwaHcAQs4R9nfCUhn-OSwuKd8_RpCTw',
    appId: '1:551556042270:android:2b39cd72a71aab4d88280f',
    messagingSenderId: '551556042270',
    projectId: 'chikoropro',
    storageBucket: 'chikoropro.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQmOFqT_XfbXk-3x-Oh6qsaP8B2_2FZEw',
    appId: '1:551556042270:ios:8e7fd58aabe9b76988280f',
    messagingSenderId: '551556042270',
    projectId: 'chikoropro',
    storageBucket: 'chikoropro.firebasestorage.app',
    iosBundleId: 'school.management.appixia.co.zw.schoolManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQmOFqT_XfbXk-3x-Oh6qsaP8B2_2FZEw',
    appId: '1:551556042270:ios:8e7fd58aabe9b76988280f',
    messagingSenderId: '551556042270',
    projectId: 'chikoropro',
    storageBucket: 'chikoropro.firebasestorage.app',
    iosBundleId: 'school.management.appixia.co.zw.schoolManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcist4Xcc_CLd_C9Hzs8zR2kFYcjkkmbY',
    appId: '1:551556042270:web:ff364f75e62c5e0888280f',
    messagingSenderId: '551556042270',
    projectId: 'chikoropro',
    authDomain: 'chikoropro.firebaseapp.com',
    storageBucket: 'chikoropro.firebasestorage.app',
    measurementId: 'G-Y3EQ5YJRJE',
  );
}
